/*!CK:2284110031!*//*1443222378,*/

if (self.CavalryLogger) { CavalryLogger.start_js(["v7RFx"]); }

__d('isNode',[],function a(b,c,d,e,f,g){if(c.__markCompiled)c.__markCompiled();function h(i){return !!(i&&(typeof Node==='function'?i instanceof Node:typeof i==='object'&&typeof i.nodeType==='number'&&typeof i.nodeName==='string'));}f.exports=h;},null);
__d('isTextNode',['isNode'],function a(b,c,d,e,f,g,h){if(c.__markCompiled)c.__markCompiled();function i(j){return h(j)&&j.nodeType==3;}f.exports=i;},null);
__d('containsNode',['isTextNode'],function a(b,c,d,e,f,g,h){if(c.__markCompiled)c.__markCompiled();function i(j,k){if(!j||!k){return false;}else if(j===k){return true;}else if(h(j)){return false;}else if(h(k)){return i(j,k.parentNode);}else if(j.contains){return j.contains(k);}else if(j.compareDocumentPosition){return !!(j.compareDocumentPosition(k)&16);}else return false;}f.exports=i;},null);
__d('getDocumentScrollElement',[],function a(b,c,d,e,f,g){'use strict';if(c.__markCompiled)c.__markCompiled();var h=typeof navigator!=='undefined'&&navigator.userAgent.indexOf('AppleWebKit')>-1;function i(j){j=j||document;return !h&&j.compatMode==='CSS1Compat'?j.documentElement:j.body;}f.exports=i;},null);
__d('isElementNode',['isNode'],function a(b,c,d,e,f,g,h){if(c.__markCompiled)c.__markCompiled();function i(j){return h(j)&&j.nodeType==1;}f.exports=i;},null);
__d('getElementText',['isElementNode','isTextNode'],function a(b,c,d,e,f,g,h,i){if(c.__markCompiled)c.__markCompiled();var j=null;function k(l){if(i(l)){return l.data;}else if(h(l)){if(j===null){var m=document.createElement('div');j=m.textContent!=null?'textContent':'innerText';}return l[j];}else return '';}f.exports=k;},null);
__d('DOMQuery',['CSS','containsNode','createArrayFromMixed','createObjectFrom','ge','getDocumentScrollElement','isElementNode','isNode','isTextNode'],function a(b,c,d,e,f,g,h,i,j,k,l,m,n,o,p){if(c.__markCompiled)c.__markCompiled();function q(s,t){return s.hasAttribute?s.hasAttribute(t):s.getAttribute(t)!==null;}var r={find:function(s,t){var u=r.scry(s,t);return u[0];},findPushSafe:function(s,t,u){var v=r.scry(s,t),w=r.scry(s,u),x;if(v.length===1&&w.length===1&&v[0]===w[0]){x=v;}else x=v.concat(w);return x[0];},scry:function(s,t){if(!s||!s.getElementsByTagName)return [];var u=t.split(' '),v=[s];for(var w=0;w<u.length;w++){if(v.length===0)break;if(u[w]==='')continue;var x=u[w],y=u[w],z=[],aa=false;if(x.charAt(0)=='^')if(w===0){aa=true;x=x.slice(1);}else return [];x=x.replace(/\[(?:[^=\]]*=(?:"[^"]*"|'[^']*'))?|[.#]/g,' $&');var ba=x.split(' '),ca=ba[0]||'*',da=ca=='*',ea=ba[1]&&ba[1].charAt(0)=='#';if(ea){var fa=l(ba[1].slice(1),s,ca);if(fa&&(da||fa.tagName.toLowerCase()==ca))for(var ga=0;ga<v.length;ga++)if(aa&&r.contains(fa,v[ga])){z=[fa];break;}else if(document==v[ga]||r.contains(v[ga],fa)&&v[ga]!==fa){z=[fa];break;}}else{var ha=[],ia=v.length,ja,ka=!aa&&y.indexOf('[')<0&&document.querySelectorAll;for(var la=0;la<ia;la++){if(aa){ja=[];var ma=v[la].parentNode;while(n(ma)){if(da||ma.tagName.toLowerCase()==ca)ja.push(ma);ma=ma.parentNode;}}else if(ka){ja=v[la].querySelectorAll(y);}else ja=v[la].getElementsByTagName(ca);var na=ja.length;for(var oa=0;oa<na;oa++)ha.push(ja[oa]);}if(!ka)for(var pa=1;pa<ba.length;pa++){var qa=ba[pa],ra=qa.charAt(0)=='.',sa=qa.substring(1);for(la=0;la<ha.length;la++){var ta=ha[la];if(!ta||ta.nodeType!==1)continue;if(ra){if(!h.hasClass(ta,sa))delete ha[la];continue;}else{var ua=qa.slice(1,qa.length-1),va=ua.indexOf('=');if(va<0){if(!q(ta,ua)){delete ha[la];continue;}}else{var wa=ua.substr(0,va),xa=ua.substr(va+1);xa=xa.slice(1,xa.length-1);if(ta.getAttribute(wa)!=xa){delete ha[la];continue;}}}}}for(la=0;la<ha.length;la++)if(ha[la]){z.push(ha[la]);if(aa)break;}}v=z;}return v;},getSelection:function(){var s=window.getSelection,t=document.selection;if(s){return s()+'';}else if(t)return t.createRange().text;return null;},contains:function(s,t){s=l(s);t=l(t);typeof s==='string'||typeof t==='string';return i(s,t);},getRootElement:function(){var s=null;if(window.Quickling&&Quickling.isActive())s=l('content');return s||document.body;},isNode:function(s){return o(s);},isNodeOfType:function(s,t){var u=j(t).join('|').toUpperCase().split('|'),v=k(u);return o(s)&&s.nodeName in v;},isElementNode:function(s){return n(s);},isTextNode:function(s){return p(s);},isInputNode:function(s){return r.isNodeOfType(s,['input','textarea'])||s.contentEditable==='true';},getDocumentScrollElement:m};f.exports=r;},null);
__d('PopupLink',['DOMEvent','DOMEventListener','Popup'],function a(b,c,d,e,f,g,h,i,j){if(c.__markCompiled)c.__markCompiled();var k={listen:function(l,m,n){i.add(l,'click',function(o){new h(o).kill();j.open(l.href,m,n);});}};f.exports=k;},null);
__d('csx',[],function a(b,c,d,e,f,g){if(c.__markCompiled)c.__markCompiled();function h(i){throw new Error('csx: Unexpected class selector transformation.');}f.exports=h;},null);
__d('cx',[],function a(b,c,d,e,f,g){if(c.__markCompiled)c.__markCompiled();function h(i){throw new Error('cx: Unexpected class transformation.');}f.exports=h;},null);